### ISSUE TITLE
add pip to installer dependencies

### ISSUE THREAD

**Issue by mpacheco12** [blissland/blissflixx#34] opened 2017-07-11 16:58 UTC
When I was installing BlissFlixx the installation wasn't completed because I did have pip installed. I had to manually install it and then run the installation again. It would be nice to make the script install pip for me.

**Comment by blissland** [comment] 2017-07-12 08:16
The configure.sh already installs pip

Line 54 (configure.sh)

`apt-get -y install python-pip`

Not sure why it did not work in your setup.

**Comment by diegorodriguezv** [comment] 2019-06-11 19:31
Hello @mpacheco12. It's been quite a while since you opened this. I'm going to close it as there is no actionable info to proceed. Feel free to open a new issue with more information including an accurate way to reproduce the problem and I'll gladly help.

**Closed by diegorodriguezv** 2019-06-11 19:31 UTC
