### ISSUE TITLE
New branch with headless setup

### ISSUE THREAD

**Issue by omody** [blissland/blissflixx#44] opened 2019-05-12 14:38 UTC
I have created a new branch from this amazing project and added SBS On Demand and ABC iView Australia and included a headless setup as well.
The ./configure.sh is also updated to work with latest Raspbian OS.
https://github.com/omody/Royalbox

**Comment by diegorodriguezv** [comment] 2019-06-11 19:51
Hello, @omody. Thanks for the heads up. It would be nice if you could contribute some of the enhancements you made back to this project.
I'm closing this as it is clearly not a bug in blissflixx but feel free to open a new one if trouble arises and I'll try to help.

**Closed by diegorodriguezv** 2019-06-11 19:51 UTC
