### ISSUE TITLE
Process suddenly died when trying to open magnet links

### ISSUE THREAD

**Issue by mauropalsgraaf** [blissland/blissflixx#37] opened 2017-08-12 14:22 UTC
Whenever I try to open a magnet link, the application shows me that the process suddenly died. After googling I've found an old post regarding the same issue: http://forum.blissflixx.rocks/archive/index.php?thread-1195.html. 

Only, the path-exists package is no longer in use in fs-chunk-store.

Any clue whats going wrong?

Running the example of peerflix in the terminal results in the following:

```
/usr/local/lib/node_modules/peerflix/node_modules/parse-torrent/index.js:110
;(function () { Buffer.alloc(0) })()
                       ^

TypeError: Buffer.alloc is not a function
    at /usr/local/lib/node_modules/peerflix/node_modules/parse-torrent/index.js:110:24
    at Object.<anonymous> (/usr/local/lib/node_modules/peerflix/node_modules/parse-torrent/index.js:110:35)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/peerflix/app.js:14:20)
    at Module._compile (module.js:435:26)
```

**Comment by mauropalsgraaf** [comment] 2017-08-12 20:20
So, I've been looking into it and it seems like the Node version was outdated and the buffer.alloc didn't exist yet. I've upgraded to the latest version v8+ and it works now. I can't seem to find the link that gave me the information, but if I remember correctly, nodejs version must be 4.5 or higher.

Besides that, it still doesn't work properly. No errors, but it loads endlessly, I gave it a try for 10 minutes+.

Maybe someone knows how to resolve an issue like this?

**Comment by diegorodriguezv** [comment] 2019-06-11 19:24
Hello @mauropalsgraaf . It's been a while since you opened this. I hope your issue has been resolved by updating blissflixx or your pi. I'm going to close this issue as there is no actionable info to move on. If you have any more trouble please feel free to post another one including an accurate way to reproduce the problem and I'll gladly help.

**Closed by diegorodriguezv** 2019-06-11 19:24 UTC
